### ISSUE TITLE
"object cannot be interpreted as an integer"

### ISSUE THREAD

**Issue by adam-hartshorne** [pedro-r-marques/keras-opt#4]
There is an issue in a couple parts of the code, which I believe is dependant on which version of numpy you have installed.

In __init__ and _update_weights methods of ScipyOptimizer

  File "...keras_opt\scipy_optimizer.py", line 132, in _collect_weights
    x_values = np.empty(self._weights_size)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

Depending on which version, you appear to need to have for example:

w_size = np.prod(shape).astype(int)

**Comment by pedro-r-marques** [comment]
Would it be possible for you to provide a set of versions that cause this issue ?
The unittests run successfully for me with python 3.6 and an environment that pulls current versions of all the dependent libraries.

**Comment by adam-hartshorne** [comment]
My Tensorflow 1.14 environment is running python 3.7 and numpy 1.16.4. The Tensorflow 2.0 nightly is running python 3.6 and also numpy 1.16.4.

For TF 1.14, the following works ok :
            `self._weights_size = self._weights_size`
For TF 2.0 nightly, I have to change it to this :
            `self._weights_size = self._weights_size.astype(int)`

**Comment by pedro-r-marques** [comment]
Targeting tensorflow 2.3+.
